<?php
/**
 * Magensky_Admintools
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Magento Team
 * that is bundled with this package of Magensky.
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * Contact us Support does not guarantee correct work of this package
 * on any other Magento edition except Magento COMMUNITY edition.
 * =================================================================
 *
 * @category    Magensky
 * @package     Magensky_Admintools
 * @website   	Magensky.com
 * @Author: 	sontung.x305@gmail.com
 **/
class Magensky_Admintools_Block_Adminhtml_Sales_Order_Grid extends Mage_Adminhtml_Block_Sales_Order_Grid
{
    public function __construct()
    {
        parent::__construct();

    }
    protected function _prepareMassaction()
    {
        parent::_prepareMassaction();
        if(Mage::helper('admintools')->isDeleteOrderActive()) {
            $this->getMassactionBlock()->addItem('delete_order', array(
                'label'=> Mage::helper('sales')->__('Delete Order'),
                'url'  => $this->getUrl('*/deleteorder/massDelete'),
                'confirm'  => Mage::helper('sales')->__('Are you sure you want to delete order?')
            ));
        }
        return $this;
    }
    protected function _prepareColumns()
    {
        parent::_prepareColumns(); // TODO: Change the autogenerated stub
        if(Mage::helper('admintools')->isDeleteOrderActive()) {
            $this->removeColumn('action');
            $this->addColumn('action',
                array(
                    'header'    => Mage::helper('sales')->__('Action'),
                    'width'     => '100px',
                    'type'      => 'action',
                    'getter'     => 'getId',
                    'renderer'  => 'admintools/adminhtml_sales_order_render_delete',
                    'filter'    => false,
                    'sortable'  => false,
                    'index'     => 'stores',
                    'is_system' => true,
                ));
        }
        return $this;
    }
}
?>
